export interface Transaction {
  id: string;
  date: string;
  description: string;
  amount: number;
  currency: string;
  type: "income" | "expense";
  category: string;
  accountId: string;
}

export const transactions: Transaction[] = [
  // === INCOME ===
  // Stripe payouts (~$18,400 total)
  {
    id: "txn-001",
    date: "2026-02-03",
    description: "Stripe Payout — Feb Week 1",
    amount: 4200,
    currency: "USD",
    type: "income",
    category: "Revenue",
    accountId: "stripe",
  },
  {
    id: "txn-002",
    date: "2026-02-10",
    description: "Stripe Payout — Feb Week 2",
    amount: 4800,
    currency: "USD",
    type: "income",
    category: "Revenue",
    accountId: "stripe",
  },
  {
    id: "txn-003",
    date: "2026-02-17",
    description: "Stripe Payout — Feb Week 3",
    amount: 5100,
    currency: "USD",
    type: "income",
    category: "Revenue",
    accountId: "stripe",
  },
  {
    id: "txn-004",
    date: "2026-02-24",
    description: "Stripe Payout — Feb Week 4",
    amount: 4300,
    currency: "USD",
    type: "income",
    category: "Revenue",
    accountId: "stripe",
  },
  // Crypto wallet payments ($3,500)
  {
    id: "txn-005",
    date: "2026-02-07",
    description: "Crypto payment — Enterprise client (Example Client A)",
    amount: 2000,
    currency: "USDC",
    type: "income",
    category: "Revenue",
    accountId: "crypto-wallet-usdc",
  },
  {
    id: "txn-006",
    date: "2026-02-19",
    description: "Crypto payment — Client (Example Client B)",
    amount: 1500,
    currency: "USDC",
    type: "income",
    category: "Revenue",
    accountId: "crypto-wallet-usdc",
  },
  // Direct bank transfers ($1,500)
  {
    id: "txn-007",
    date: "2026-02-12",
    description: "Bank Transfer — Annual license (Example Client C)",
    amount: 1500,
    currency: "EUR",
    type: "income",
    category: "Revenue",
    accountId: "mercury-bank",
  },

  // === EXPENSES ===
  // SaaS subscriptions ($2,100)
  {
    id: "txn-008",
    date: "2026-02-01",
    description: "AWS Services",
    amount: 685,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "mercury-bank",
  },
  {
    id: "txn-009",
    date: "2026-02-01",
    description: "OpenAI API",
    amount: 340,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-010",
    date: "2026-02-02",
    description: "Anthropic API",
    amount: 230,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-011",
    date: "2026-02-01",
    description: "Datadog",
    amount: 145,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-012",
    date: "2026-02-01",
    description: "Ahrefs Lite",
    amount: 99,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-013",
    date: "2026-02-01",
    description: "Intercom Starter",
    amount: 89,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-014",
    date: "2026-02-01",
    description: "Mixpanel Growth",
    amount: 89,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-015",
    date: "2026-02-01",
    description: "Supabase Pro",
    amount: 75,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-016",
    date: "2026-02-01",
    description: "HubSpot CRM",
    amount: 50,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-017",
    date: "2026-02-01",
    description: "Sentry Developer",
    amount: 52,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-018",
    date: "2026-02-01",
    description: "Cloudflare Pro",
    amount: 45,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-019",
    date: "2026-02-01",
    description: "Crisp Chat",
    amount: 45,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-020",
    date: "2026-02-01",
    description: "Resend Email",
    amount: 35,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-021",
    date: "2026-02-01",
    description: "Vercel Pro",
    amount: 20,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-022",
    date: "2026-02-01",
    description: "Notion Team",
    amount: 16,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-023",
    date: "2026-02-01",
    description: "Figma Professional",
    amount: 15,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-024",
    date: "2026-02-01",
    description: "Loom Business",
    amount: 15,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-025",
    date: "2026-02-01",
    description: "Slack Pro",
    amount: 12.50,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-026",
    date: "2026-02-01",
    description: "Calendly Pro",
    amount: 12,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-027",
    date: "2026-02-01",
    description: "1Password Business",
    amount: 8,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-028",
    date: "2026-02-01",
    description: "Linear",
    amount: 8,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-029",
    date: "2026-02-01",
    description: "GitHub Team",
    amount: 14.50,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },
  {
    id: "txn-030",
    date: "2026-02-01",
    description: "PostHog (free tier)",
    amount: 0,
    currency: "USD",
    type: "expense",
    category: "SaaS Subscriptions",
    accountId: "stripe",
  },

  // Contractor payments ($3,200 total)
  {
    id: "txn-031",
    date: "2026-02-05",
    description: "Contractor — Example Contractor B (design)",
    amount: 1200,
    currency: "USDC",
    type: "expense",
    category: "Contractors",
    accountId: "crypto-wallet-usdc",
  },
  {
    id: "txn-032",
    date: "2026-02-15",
    description: "Contractor — Example Contractor A (backend dev)",
    amount: 1500,
    currency: "EUR",
    type: "expense",
    category: "Contractors",
    accountId: "mercury-bank",
  },
  {
    id: "txn-033",
    date: "2026-02-20",
    description: "Contractor — Example Contractor C (copywriting)",
    amount: 500,
    currency: "USDC",
    type: "expense",
    category: "Contractors",
    accountId: "crypto-wallet-usdc",
  },

  // Cloud & Hosting ($450)
  {
    id: "txn-034",
    date: "2026-02-01",
    description: "Hetzner Dedicated Server",
    amount: 180,
    currency: "EUR",
    type: "expense",
    category: "Cloud & Hosting",
    accountId: "mercury-bank",
  },
  {
    id: "txn-035",
    date: "2026-02-01",
    description: "DigitalOcean Managed DB",
    amount: 150,
    currency: "USD",
    type: "expense",
    category: "Cloud & Hosting",
    accountId: "stripe",
  },
  {
    id: "txn-036",
    date: "2026-02-01",
    description: "Bunny CDN",
    amount: 120,
    currency: "USD",
    type: "expense",
    category: "Cloud & Hosting",
    accountId: "stripe",
  },

  // Marketing ($800)
  {
    id: "txn-037",
    date: "2026-02-03",
    description: "Google Ads",
    amount: 400,
    currency: "USD",
    type: "expense",
    category: "Marketing",
    accountId: "mercury-bank",
  },
  {
    id: "txn-038",
    date: "2026-02-10",
    description: "Twitter/X Ads",
    amount: 250,
    currency: "USD",
    type: "expense",
    category: "Marketing",
    accountId: "mercury-bank",
  },
  {
    id: "txn-039",
    date: "2026-02-14",
    description: "Sponsored Newsletter — Indie Hackers Weekly",
    amount: 150,
    currency: "USD",
    type: "expense",
    category: "Marketing",
    accountId: "mercury-bank",
  },

  // Banking Fees ($150)
  {
    id: "txn-040",
    date: "2026-02-01",
    description: "Mercury Bank — Monthly fee",
    amount: 50,
    currency: "EUR",
    type: "expense",
    category: "Banking Fees",
    accountId: "mercury-bank",
  },
  {
    id: "txn-041",
    date: "2026-02-01",
    description: "Stripe Processing Fees",
    amount: 75,
    currency: "USD",
    type: "expense",
    category: "Banking Fees",
    accountId: "stripe",
  },
  {
    id: "txn-042",
    date: "2026-02-01",
    description: "Crypto Transaction Fees",
    amount: 25,
    currency: "USD",
    type: "expense",
    category: "Banking Fees",
    accountId: "crypto-wallet-usdc",
  },

  // Other ($500)
  {
    id: "txn-043",
    date: "2026-02-08",
    description: "Coworking Space — Chiang Mai",
    amount: 200,
    currency: "USD",
    type: "expense",
    category: "Other",
    accountId: "mercury-bank",
  },
  {
    id: "txn-044",
    date: "2026-02-11",
    description: "Legal Consultation — Estonian Tax",
    amount: 200,
    currency: "EUR",
    type: "expense",
    category: "Other",
    accountId: "mercury-bank",
  },
  {
    id: "txn-045",
    date: "2026-02-22",
    description: "Domain Renewals (3 domains)",
    amount: 100,
    currency: "USD",
    type: "expense",
    category: "Other",
    accountId: "stripe",
  },

  // Crypto on-ramp / off-ramp transfers
  {
    id: "txn-046",
    date: "2026-02-09",
    description: "Crypto off-ramp — USDC to EUR",
    amount: 5000,
    currency: "USDC",
    type: "expense",
    category: "Transfer",
    accountId: "crypto-wallet-usdc",
  },
  {
    id: "txn-047",
    date: "2026-02-16",
    description: "Crypto on-ramp — EUR to USDC",
    amount: 3000,
    currency: "EUR",
    type: "expense",
    category: "Transfer",
    accountId: "crypto-wallet-usdc",
  },
];

export const incomeTransactions = transactions.filter(
  (t) => t.type === "income"
);
export const expenseTransactions = transactions.filter(
  (t) => t.type === "expense" && t.category !== "Transfer"
);
