export interface Jurisdiction {
  id: string;
  name: string;
  flag: string;
  corpTaxRate: string;
  corpTaxNote?: string;
  setupCost: number;
  ongoingCostYear: number;
  bankingEase: "Easy" | "Medium" | "Hard";
  cryptoFriendliness: "Friendly" | "Medium" | "Complex" | "Restricted";
  taxReporting: "Annual" | "Quarterly" | "Monthly";
  specialRegime?: string;
  estimatedSavings: number;
  pros: string[];
  cons: string[];
}

export const jurisdictions: Jurisdiction[] = [
  {
    id: "georgia",
    name: "Georgia",
    flag: "\u{1F1EC}\u{1F1EA}",
    corpTaxRate: "1%",
    corpTaxNote: "1% for small business status (revenue under ~$155K/yr)",
    setupCost: 500,
    ongoingCostYear: 100,
    bankingEase: "Easy",
    cryptoFriendliness: "Friendly",
    taxReporting: "Annual",
    specialRegime: "Small Business Status — 1% on gross revenue",
    estimatedSavings: 12000,
    pros: [
      "1% effective tax rate for small businesses",
      "Extremely low setup and ongoing costs",
      "Easy bank account opening",
      "Crypto-friendly regulation",
      "No CFC rules for most nationalities",
      "English widely spoken in business",
    ],
    cons: [
      "Small business status has revenue cap (~$155K/yr)",
      "Less prestigious jurisdiction",
      "Limited double tax treaty network",
      "Banking infrastructure less developed than EU",
    ],
  },
  {
    id: "estonia",
    name: "Estonia",
    flag: "\u{1F1EA}\u{1F1EA}",
    corpTaxRate: "0% / 20%",
    corpTaxNote: "0% on retained earnings, 20% on distributed profits",
    setupCost: 500,
    ongoingCostYear: 200,
    bankingEase: "Medium",
    cryptoFriendliness: "Friendly",
    taxReporting: "Annual",
    specialRegime: "e-Residency program — 0% on retained earnings",
    estimatedSavings: 14000,
    pros: [
      "0% tax on retained earnings",
      "e-Residency program for remote management",
      "EU jurisdiction with full EU market access",
      "Fully digital government services",
      "Strong tech ecosystem and reputation",
      "Simple annual reporting",
    ],
    cons: [
      "20% tax when distributing profits",
      "Bank account opening can be challenging remotely",
      "Requires local service provider for compliance",
      "EU reporting requirements (DAC7, etc.)",
    ],
  },
  {
    id: "us-wyoming",
    name: "US — Wyoming",
    flag: "\u{1F1FA}\u{1F1F8}",
    corpTaxRate: "0% state + 21% federal",
    corpTaxNote: "No state income tax; 21% federal corporate tax applies",
    setupCost: 200,
    ongoingCostYear: 50,
    bankingEase: "Easy",
    cryptoFriendliness: "Complex",
    taxReporting: "Quarterly",
    specialRegime: "DAO LLC available; no state income tax",
    estimatedSavings: -2000,
    pros: [
      "Zero state income tax",
      "Very low setup and maintenance costs",
      "Easy access to US banking (Mercury, SVB)",
      "Strong legal framework",
      "DAO LLC structure available",
      "Best for US-facing businesses",
    ],
    cons: [
      "21% federal corporate tax",
      "Complex tax filing requirements",
      "Crypto regulations evolving and complex",
      "Requires registered agent",
      "FATCA reporting obligations",
    ],
  },
  {
    id: "us-delaware",
    name: "US — Delaware",
    flag: "\u{1F1FA}\u{1F1F8}",
    corpTaxRate: "8.7% state + 21% federal",
    corpTaxNote: "8.7% state tax + 21% federal; C-Corp default",
    setupCost: 300,
    ongoingCostYear: 300,
    bankingEase: "Easy",
    cryptoFriendliness: "Complex",
    taxReporting: "Quarterly",
    specialRegime: "Court of Chancery for business disputes",
    estimatedSavings: -2500,
    pros: [
      "Gold standard for VC-backed companies",
      "Court of Chancery (specialized business court)",
      "Well-established corporate law",
      "Easy US banking access",
      "Most familiar to US investors",
    ],
    cons: [
      "21% federal + 8.7% state tax (if nexus)",
      "Annual franchise tax ($400 minimum)",
      "Complex compliance requirements",
      "Overkill for solo founders without US investors",
      "Expensive compared to Wyoming",
    ],
  },
  {
    id: "uae-freezone",
    name: "UAE Free Zone",
    flag: "\u{1F1E6}\u{1F1EA}",
    corpTaxRate: "0-9%",
    corpTaxNote: "0% on income under AED 375K (~$102K); 9% above",
    setupCost: 5000,
    ongoingCostYear: 2000,
    bankingEase: "Medium",
    cryptoFriendliness: "Friendly",
    taxReporting: "Annual",
    specialRegime: "Free Zone — 0% corporate tax under threshold",
    estimatedSavings: 15000,
    pros: [
      "0% tax under $102K, 9% above (very competitive)",
      "Crypto-friendly (VARA regulated)",
      "Growing tech and startup ecosystem",
      "No personal income tax",
      "Good banking options (Wio, ADCB, etc.)",
      "Tax treaties with 100+ countries",
    ],
    cons: [
      "High setup cost ($5K+)",
      "Ongoing visa and license renewal costs",
      "Bank account opening requires physical presence",
      "9% on income above threshold",
      "Living costs in Dubai are high",
    ],
  },
  {
    id: "portugal",
    name: "Portugal",
    flag: "\u{1F1F5}\u{1F1F9}",
    corpTaxRate: "14.5-21%",
    corpTaxNote: "14.5% on first \u20AC50K (SME), up to 21% standard rate",
    setupCost: 3000,
    ongoingCostYear: 1500,
    bankingEase: "Easy",
    cryptoFriendliness: "Friendly",
    taxReporting: "Annual",
    specialRegime: "SME reduced rate (14.5% on first \u20AC50K)",
    estimatedSavings: 2000,
    pros: [
      "EU jurisdiction",
      "Reduced SME rate on first \u20AC50K",
      "Historically crypto-friendly",
      "Great quality of life",
      "Growing tech/startup scene",
      "Easy banking access",
    ],
    cons: [
      "NHR tax regime expired in 2024",
      "Standard 21% rate on higher profits",
      "Social security contributions for directors",
      "Relatively high ongoing compliance costs",
      "New crypto taxation rules post-2023",
    ],
  },
  {
    id: "uk",
    name: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    corpTaxRate: "19-25%",
    corpTaxNote: "19% on profits under \u00A350K; 25% over \u00A3250K; marginal between",
    setupCost: 100,
    ongoingCostYear: 200,
    bankingEase: "Easy",
    cryptoFriendliness: "Medium",
    taxReporting: "Quarterly",
    estimatedSavings: -1000,
    pros: [
      "Very low setup cost",
      "Small profits rate (19%)",
      "Excellent banking infrastructure",
      "Strong legal framework",
      "Large double tax treaty network",
      "Easy to open company remotely",
    ],
    cons: [
      "25% rate on profits above \u00A3250K",
      "VAT registration required at \u00A390K threshold",
      "Making Tax Digital requirements",
      "Quarterly reporting obligations",
      "Crypto gains taxable",
    ],
  },
  {
    id: "singapore",
    name: "Singapore",
    flag: "\u{1F1F8}\u{1F1EC}",
    corpTaxRate: "17%",
    corpTaxNote: "17% headline; partial exemption on first S$200K",
    setupCost: 2000,
    ongoingCostYear: 1500,
    bankingEase: "Medium",
    cryptoFriendliness: "Friendly",
    taxReporting: "Annual",
    specialRegime: "Partial tax exemption — 75% off first S$10K, 50% off next S$190K",
    estimatedSavings: 3000,
    pros: [
      "Strong reputation and credibility",
      "Partial tax exemption for startups",
      "No capital gains tax",
      "Extensive double tax treaty network",
      "Crypto-friendly (MAS regulated)",
      "Asia-Pacific gateway",
    ],
    cons: [
      "17% headline rate",
      "Requires local director or nominee",
      "Higher setup and ongoing costs",
      "Bank account opening requires due diligence",
      "GST registration at S$1M threshold",
    ],
  },
  {
    id: "hong-kong",
    name: "Hong Kong",
    flag: "\u{1F1ED}\u{1F1F0}",
    corpTaxRate: "8.25% / 16.5%",
    corpTaxNote: "8.25% on first HK$2M (~$256K); 16.5% above",
    setupCost: 1500,
    ongoingCostYear: 1000,
    bankingEase: "Medium",
    cryptoFriendliness: "Friendly",
    taxReporting: "Annual",
    specialRegime: "Two-tiered profits tax — 8.25% on first HK$2M",
    estimatedSavings: 8000,
    pros: [
      "Low effective tax rate for small companies",
      "Territorial tax system (offshore income exempt)",
      "No capital gains tax, no VAT",
      "Strong banking infrastructure",
      "Crypto-friendly regulations",
      "Gateway to Chinese market",
    ],
    cons: [
      "Requires annual audit",
      "Bank account opening increasingly difficult remotely",
      "Political uncertainty",
      "Nominee director may be needed",
      "Substance requirements increasing",
    ],
  },
  {
    id: "panama",
    name: "Panama",
    flag: "\u{1F1F5}\u{1F1E6}",
    corpTaxRate: "0% (foreign income)",
    corpTaxNote: "Territorial tax system — 0% on all foreign-sourced income",
    setupCost: 2000,
    ongoingCostYear: 500,
    bankingEase: "Hard",
    cryptoFriendliness: "Medium",
    taxReporting: "Annual",
    specialRegime: "Territorial tax — only Panama-sourced income taxed",
    estimatedSavings: 13000,
    pros: [
      "0% tax on foreign-sourced income",
      "Strong privacy protections",
      "USD as legal tender",
      "Low ongoing costs",
      "No CFC legislation",
      "Friendly residency options",
    ],
    cons: [
      "Difficult to open bank accounts",
      "Reputation concerns (FATF grey list history)",
      "Limited double tax treaty network",
      "Physical presence often required for banking",
      "Increasing international scrutiny",
    ],
  },
];

export const recommendedJurisdiction = "georgia";

export function getJurisdictionById(id: string): Jurisdiction | undefined {
  return jurisdictions.find((j) => j.id === id);
}

export function getRecommendedJurisdiction(): Jurisdiction {
  return jurisdictions.find((j) => j.id === recommendedJurisdiction)!;
}
