import {
  assertValidRoutineSources,
  type RoutineSourceDefinition,
} from "@/lib/routines/source-registry";

export const BKPM_LEGAL_WATCH_ROUTINE_SLUG = "legal_watch_bkpm";
export const BKPM_LEGAL_WATCH_JURISDICTION = "ID";
export const BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF = "2026-05-28";

const PRIMARY_LEGAL_PROVENANCE_REQUIREMENTS = [
  "source_url",
  "authority",
  "jurisdiction",
  "retrieved_at",
  "review_status",
  "source_date_or_retrieved_date",
  "supersession_check",
];

const OFFICIAL_SUPPORT_PROVENANCE_REQUIREMENTS = [
  ...PRIMARY_LEGAL_PROVENANCE_REQUIREMENTS,
  "primary_source_verification",
];

export const BKPM_LEGAL_WATCH_SOURCES = assertValidRoutineSources([
  {
    sourceKey: "jdih-bkpm",
    title: "JDIH BKPM / Ministry of Investment",
    url: "https://jdih.bkpm.go.id/",
    sourceType: "manual_seed",
    authority: "BKPM",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["bkpm", "regulations", "supersession"],
    fetchMode: "http_html",
    checkFrequency: "weekly",
    stalenessRisk: "high",
    trustTier: "primary",
    status: "active",
    allowedContentTypes: ["text/html"],
    allowedUrlPrefixes: ["https://jdih.bkpm.go.id/"],
    discoveryOnly: true,
    primarySourceRequired: true,
    useFor:
      "BKPM / Ministry of Investment regulations, circulars, official legal products, supersession checks, and agency-level legal metadata.",
    provenanceRequirements: PRIMARY_LEGAL_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Use daily rechecks when a BKPM regulation change is suspected.",
      "Root page exposes latest Produk Hukum and should be crawled as the JDIH legal-product discovery page.",
    ],
    metadata: {
      collectorProvider: "apify",
      apifyActorId: "apify/website-content-crawler",
      apifyCrawlerType: "playwright:adaptive",
      apifyMaxPagesPerRun: 5,
      apifyWaitForFinishSecs: 120,
      apifyRequestTimeoutSecs: 60,
      apifyUseProxy: true,
      apifyIncludeUrlGlobs: [
        "https://jdih.bkpm.go.id/id/document/**",
        "https://jdih.bkpm.go.id/en/document/**",
      ],
      operatorInstructions:
        "Watch latest legal products, especially OSS, BKPM licensing, investment facilities, sanctions, LKPM, and supersession signals.",
      sourceLanguage: "id",
    },
  },
  {
    sourceKey: "bkpm-press-release-watch",
    title: "BKPM official press-release listing",
    url: "https://bkpm.go.id/id/info/siaran-pers",
    sourceType: "official_news",
    authority: "BKPM",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["bkpm", "oss-rba", "kbli", "licensing", "official-news"],
    fetchMode: "http_html",
    checkFrequency: "daily",
    stalenessRisk: "high",
    trustTier: "official",
    status: "active",
    allowedContentTypes: ["text/html", "application/pdf"],
    allowedUrlPrefixes: ["https://bkpm.go.id/id/info/siaran-pers"],
    primarySourceRequired: true,
    useFor:
      "BKPM press releases that announce OSS, KBLI, PP 28/2025, NIB, LKPM, investment licensing, and implementation policy changes.",
    provenanceRequirements: OFFICIAL_SUPPORT_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Verified listing shows dated press releases, including PP 28/2025 OSS adjustment and KBLI 2025 implementation releases.",
      "Ignore generic investment-event releases unless they change OSS, licensing, KBLI, LKPM, or compliance obligations.",
    ],
    metadata: {
      collectorProvider: "apify",
      apifyActorId: "apify/website-content-crawler",
      apifyCrawlerType: "playwright:adaptive",
      apifyMaxPagesPerRun: 5,
      apifyWaitForFinishSecs: 120,
      apifyRequestTimeoutSecs: 60,
      apifyUseProxy: true,
      apifyIncludeUrlGlobs: [
        "https://bkpm.go.id/id/info/siaran-pers/**",
      ],
      operatorInstructions:
        "Create candidates only for press releases that affect OSS/RBA licensing, KBLI migration, NIB, LKPM, PP 28/2025, BKPM legal process, or company compliance.",
      sourceLanguage: "id",
    },
  },
  {
    sourceKey: "permen-investasi-bkpm-5-2025",
    title: "Permen Investhil / Kepala BKPM No. 5 Tahun 2025",
    url: "https://jdih.bkpm.go.id/en/document/peraturan-menteri-investasi-dan-hilirisasikepala-badan-koordinasi-penanaman-modal-nomor-5-tahun-2025-tentang-pedoman-dan-tata-cara-penyelenggaraan-perizinan-berusaha-berbasis-risiko-dan-fas",
    sourceType: "regulation",
    authority: "BKPM",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["bkpm", "oss-rba", "licensing", "supersession"],
    fetchMode: "http_html",
    checkFrequency: "weekly",
    stalenessRisk: "high",
    trustTier: "primary",
    status: "active",
    allowedContentTypes: ["text/html", "application/pdf"],
    instrumentNumber: "5/2025",
    useFor:
      "Current BKPM risk-based licensing procedures and explicit replacement or supersession of older BKPM licensing regulations.",
    provenanceRequirements: PRIMARY_LEGAL_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Immediate recheck when the JDIH BKPM registry changes.",
    ],
  },
  {
    sourceKey: "pp-28-2025",
    title: "PP No. 28 Tahun 2025 on risk-based business licensing",
    url: "https://jdih.bpkp.go.id/pencarian/5529/detail",
    sourceType: "regulation",
    authority: "BPKP JDIH / JDIH Setneg",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["oss-rba", "licensing", "risk-based-licensing"],
    fetchMode: "http_html",
    checkFrequency: "weekly",
    stalenessRisk: "high",
    trustTier: "primary",
    status: "active",
    allowedContentTypes: ["text/html", "application/pdf"],
    instrumentNumber: "PP 28/2025",
    useFor:
      "National-level OSS RBA licensing basis and supersession of earlier government regulations.",
    provenanceRequirements: PRIMARY_LEGAL_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Uses the BPKP JDIH detail page as an alternate official source when the primary source is unavailable.",
      "The source metadata cites JDIH Setneg as the underlying official source.",
    ],
  },
  {
    sourceKey: "perpres-10-2021-bpk",
    title: "BPK regulation database entry for Perpres No. 10 Tahun 2021",
    url: "https://jdih.bpkp.go.id/produkhukum/552/detail",
    sourceType: "regulation",
    authority: "BPKP JDIH / JDIH Setneg",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["foreign-ownership", "investment-fields", "restrictions"],
    fetchMode: "http_html",
    checkFrequency: "weekly",
    stalenessRisk: "medium",
    trustTier: "official",
    status: "active",
    allowedContentTypes: ["text/html", "application/pdf"],
    instrumentNumber: "Perpres 10/2021",
    primarySourceRequired: true,
    useFor:
      "Cross-checking status, amendment links, downloadable regulation text, and investment-business-field restrictions.",
    provenanceRequirements: OFFICIAL_SUPPORT_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Use as a cross-check, not the only authority for promoted legal conclusions.",
      "Uses the BPKP JDIH detail page as an alternate official source when automated access to the primary source is unavailable.",
    ],
  },
  {
    sourceKey: "oss-guidance-manuals",
    title: "OSS Indonesia official guidance and manuals",
    url: "https://oss.go.id/id/panduan?lang=id",
    sourceType: "official_guidance",
    authority: "OSS",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["oss-rba", "nib", "lkpm", "licensing"],
    fetchMode: "http_html",
    checkFrequency: "weekly",
    stalenessRisk: "high",
    trustTier: "official",
    status: "active",
    allowedContentTypes: ["text/html", "application/pdf"],
    primarySourceRequired: true,
    useFor:
      "Practical OSS flow, NIB, licensing, LKPM, user-guide evidence, and operational steps.",
    provenanceRequirements: OFFICIAL_SUPPORT_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Use daily rechecks during known OSS releases.",
      "Operational guidance still needs the underlying regulation before creating obligations or sanctions.",
    ],
    metadata: {
      collectorProvider: "apify",
      apifyActorId: "apify/website-content-crawler",
      apifyCrawlerType: "playwright:adaptive",
      apifyMaxPagesPerRun: 3,
      apifyWaitForFinishSecs: 120,
      apifyRequestTimeoutSecs: 60,
      apifyUseProxy: true,
      apifyIncludeUrlGlobs: [
        "https://oss.go.id/id/panduan/**",
        "https://oss.go.id/en/panduan/**",
      ],
      operatorInstructions:
        "Watch for new or changed OSS manuals that alter NIB, KBLI, LKPM, permit amendment, sanction, verification, or transition workflows.",
      sourceLanguage: "id",
    },
  },
  {
    sourceKey: "oss-announcements-watch",
    title: "OSS Indonesia official announcements",
    url: "https://oss.go.id/id/pengumuman",
    sourceType: "official_news",
    authority: "OSS",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["oss-rba", "announcements", "kbli", "licensing"],
    fetchMode: "http_html",
    checkFrequency: "daily",
    stalenessRisk: "high",
    trustTier: "official",
    status: "active",
    allowedContentTypes: ["text/html", "application/pdf"],
    allowedUrlPrefixes: ["https://oss.go.id/"],
    primarySourceRequired: true,
    useFor:
      "OSS announcement listing and announcement details for operational changes, PP 28/2025 transition notes, RDTR/KBLI updates, and licensing workflow notices.",
    provenanceRequirements: OFFICIAL_SUPPORT_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Verified listing includes dated announcements such as PP 28/2025 post-effect notice, RDTR/KBLI updates, and OSS transition guidance.",
      "Use as operational notice evidence; require primary regulation for legal obligations or sanctions.",
    ],
    metadata: {
      collectorProvider: "apify",
      apifyActorId: "apify/website-content-crawler",
      apifyCrawlerType: "playwright:adaptive",
      apifyMaxPagesPerRun: 5,
      apifyWaitForFinishSecs: 120,
      apifyRequestTimeoutSecs: 60,
      apifyUseProxy: true,
      apifyIncludeUrlGlobs: [
        "https://oss.go.id/id/pengumuman/**",
        "https://oss.go.id/pengumuman/**",
      ],
      operatorInstructions:
        "Track announcement detail pages for OSS/RBA licensing, PP 28/2025, KBLI, RDTR, NIB, LKPM, and permit-transition changes.",
      sourceLanguage: "id",
    },
  },
  {
    sourceKey: "bps-kbli-2025",
    title: "Peraturan BPS No. 7 Tahun 2025 on KBLI 2025",
    url: "https://jdih.bps.go.id/public/dokumen-hukum/eyJpdiI6Im1wWWpoQWdlNGJCRzBuek0vL0dQZ0E9PSIsInZhbHVlIjoidmpFU0lzWVFtc0d5d21oc0MrN0h6QT09IiwibWFjIjoiZWExODYzNzcwYzZmMjBhNmFiODgxOTAxZGZhYzQ0MzhhN2MzNTA1Mzk2YzhkYzI0MDBiYWI1YTQ1NzNkZGE4ZSIsInRhZyI6IiJ9",
    sourceType: "regulation",
    authority: "BPS JDIH",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["kbli", "classification", "oss-rba"],
    fetchMode: "http_html",
    checkFrequency: "monthly",
    stalenessRisk: "medium",
    trustTier: "primary",
    status: "active",
    allowedContentTypes: ["text/html", "application/pdf"],
    instrumentNumber: "Peraturan BPS 7/2025",
    primarySourceRequired: true,
    useFor:
      "Legal basis for KBLI 2025 classification references used by OSS/BKPM licensing flows.",
    provenanceRequirements: OFFICIAL_SUPPORT_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Uses BPS JDIH as an alternate official source when the primary source is unavailable.",
      "Recheck when OSS or BKPM references KBLI changes.",
    ],
  },
  {
    sourceKey: "bps-news-kbli-watch",
    title: "BPS national news listing for KBLI implementation",
    url: "https://www.bps.go.id/id/news",
    sourceType: "official_news",
    authority: "BPS",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["kbli", "classification", "oss-rba", "official-news"],
    fetchMode: "http_html",
    checkFrequency: "weekly",
    stalenessRisk: "medium",
    trustTier: "official",
    status: "paused",
    allowedContentTypes: ["text/html"],
    allowedUrlPrefixes: ["https://www.bps.go.id/"],
    primarySourceRequired: true,
    useFor:
      "Discovery of BPS national news on KBLI 2025 implementation, conversion tables, and OSS/AHU transition rules.",
    provenanceRequirements: OFFICIAL_SUPPORT_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Paused for automation: bps.go.id listing returns Cloudflare challenge responses to local/server fetches and was unstable through Apify.",
      "Exact useful detail pages found include /id/news/2026/04/27/897/... KBLI 2020-2025 conversion and /id/news/2026/04/30/908/... no-new-license guidance.",
      "Reactivate only with a stable official BPS API, feed, or dedicated BPS adapter.",
    ],
    metadata: {
      collectorProvider: "apify",
      apifyActorId: "apify/website-content-crawler",
      apifyCrawlerType: "playwright:adaptive",
      apifyMaxPagesPerRun: 3,
      apifyWaitForFinishSecs: 120,
      apifyRequestTimeoutSecs: 60,
      apifyUseProxy: true,
      apifyIncludeUrlGlobs: [
        "https://www.bps.go.id/id/news/**",
        "https://www.bps.go.id/news/**",
      ],
      operatorInstructions:
        "Only candidate KBLI 2025, KBLI 2020-2025 conversion, OSS/AHU transition, or permit-validity news. Do not use regional BPS reposts as primary evidence.",
      sourceLanguage: "id",
    },
  },
  {
    sourceKey: "bps-kbli-2020-2025-conversion",
    title: "BPS KBLI 2020-2025 conversion table release",
    url: "https://www.bps.go.id/id/news/2026/04/27/897/bps-rilis-tabel-konversi-klasifikasi-baku-lapangan-usaha-indonesia-kbli-2020-2025-.html",
    sourceType: "official_news",
    authority: "BPS",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["kbli", "classification", "migration"],
    fetchMode: "http_html",
    checkFrequency: "monthly",
    stalenessRisk: "medium",
    trustTier: "official",
    status: "paused",
    allowedContentTypes: ["text/html"],
    primarySourceRequired: true,
    useFor:
      "Mapping old KBLI references to KBLI 2025 and detecting affected legal/company records.",
    provenanceRequirements: OFFICIAL_SUPPORT_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Paused for automated collection: bps.go.id news pages currently return Cloudflare challenge responses to server-side fetches.",
      "Reactivate only with a stable official BPS API/download endpoint.",
      "Keep monthly checks until KBLI migration is complete.",
    ],
    metadata: {
      sourceLanguage: "id",
    },
  },
  {
    sourceKey: "jdihn-discovery",
    title: "JDIHN national legal documentation network",
    url: "https://www.jdihn.go.id/",
    sourceType: "manual_seed",
    authority: "JDIHN",
    jurisdiction: BKPM_LEGAL_WATCH_JURISDICTION,
    topicTags: ["discovery", "jdih", "regulations"],
    fetchMode: "http_html",
    checkFrequency: "monthly",
    stalenessRisk: "medium",
    trustTier: "official",
    status: "paused",
    allowedContentTypes: ["text/html"],
    allowedUrlPrefixes: ["https://www.jdihn.go.id/"],
    discoveryOnly: true,
    primarySourceRequired: true,
    useFor:
      "Discovery of related JDIH entries and agency repositories.",
    provenanceRequirements: OFFICIAL_SUPPORT_PROVENANCE_REQUIREMENTS,
    verifiedAsOf: BKPM_SOURCE_REGISTRY_VERIFIED_AS_OF,
    notes: [
      "Every discovered document must be verified against the originating agency or national regulation repository.",
      "Disabled by default because availability for automated collection varies by deployment.",
    ],
  },
] satisfies RoutineSourceDefinition[]);
